INSERT INTO users (id, email, username, password, fullname, about_me, gender, date_of_birth, avatar_type, created_at)
VALUES
(
	"3e8e14d4-b252-461b-9e76-1f143079cc9f",
	"rebecca_mitchell@live.com",
	"jollybadge",
	"$2b$12$qXY0KRrZybuLtq1J/XKMCO/O1w6ENYqWSFbl6F4VbB4FMGRg3NP.G",
	"Rebecca Mitchell",
	"Hello, this is test account #6, the data is generated by https://cobbl.io",
	"female",
	"2014-09-21",
	"avatar8",
	"2025-06-19 22:49:46.361243+00:00"
),
(
	"31512621-10b4-4951-a339-3d2e505978c3",
	"owenrcollins@yahoo.com",
	"mistycrate",
	"$2b$12$Wh4l3Clgv4mn1MU/tmuGq.VsQgh6/8Qic.e2SV6IDjP9SfC7uWW8e",
	"Owen Collins",
	"Hello, this is test account #2, the data is generated by https://cobbl.io",
	"male",
	"1999-09-05",
	"avatar5",
	"2025-06-19 22:49:46.861243+00:00"
),
(
	"c4c0b028-9e89-4d16-a21d-dd9368831f7f",
	"s_m_lopez@rocketmail.com",
	"bewilderedshade",
	"$2b$12$tVp5J9tG/D7znWxfSlxYMOG6THQ6RujbW/6PMLNKonDsGpkM5gV1m",
	"Stephanie Lopez",
	"Hello, this is test account #5, the data is generated by https://cobbl.io",
	"female",
	"2021-03-19",
	"avatar10",
	"2025-06-19 22:49:47.361243+00:00"
),
(
	"270b45d1-0761-4636-8959-a3485e70b137",
	"jdrichardson@rocketmail.com",
	"dustyshelf",
	"$2b$12$LDcUw2x7zzLrIcTXGQ38T.yIBp/rSIaaK9dhHtm4hZO/Tq8qfKYGm",
	"Joseph Richardson",
	"Hello, this is test account #9, the data is generated by https://cobbl.io",
	"male",
	"2010-12-07",
	"avatar1",
	"2025-06-19 22:49:47.861243+00:00"
),
(
	"494646c1-0ec4-48de-a0cc-11f40ce527fa",
	"lking@hotmail.com",
	"stupendousliquid",
	"$2b$12$hDeb5m1J8kszq4nKf9jE.uzqs6om/Bwe.ck1M0x57CaxvjcDhvsgO",
	"Lillian King",
	"Hello, this is test account #7, the data is generated by https://cobbl.io",
	"female",
	"2005-06-21",
	"avatar6",
	"2025-06-19 22:49:48.361243+00:00"
),
(
	"b0407a9f-b516-4b45-b5a0-c1b52569fec8",
	"jasminemayperez@outlook.com",
	"feignedfrog",
	"$2b$12$mvBJz2ibR8rBxO/mpUeLje1gL7KPxshEth8bHcNPjX4w5RDZ5g.u.",
	"Jasmine Perez",
	"Hello, this is test account #8, the data is generated by https://cobbl.io",
	"female",
	"2006-12-20",
	"avatar9",
	"2025-06-19 22:49:48.861243+00:00"
),
(
	"72522e8a-e191-402f-bb19-ded1a1a11a7d",
	"ahall@yahoo.com",
	"tritehoney",
	"$2b$12$lss3ovijl/ckcUMt6vwWX.rNbFeFVRGR0yTJdtUC0CM7DBUQiWd.i",
	"Alyssa Hall",
	"Hello, this is test account #4, the data is generated by https://cobbl.io",
	"female",
	"1993-01-11",
	NULL,
	"2025-06-19 22:49:49.361243+00:00"
),
(
	"4441348d-4e0e-4cac-91f5-e2e4aeedf795",
	"ava.morgan@aol.com",
	"quicksupport",
	"$2b$12$tmEK8mKZkri4TgQc6eQvU.IGF88aHA0gk0gHKVl7atQ6ZhvulnP6y",
	"Ava Morgan",
	"Hello, this is test account #3, the data is generated by https://cobbl.io",
	"female",
	"2012-06-12",
	"avatar7",
	"2025-06-19 22:49:49.861243+00:00"
),
(
	"1572aedc-9b58-4aff-958f-18c26c4b0241",
	"l_evans@rocketmail.com",
	"miniatureriver",
	"$2b$12$NhyQEsyZhpkqdtXuBIKqteXFC9IAUUQ807jHV4Tlj2qMD4qXoVkc.",
	"Layla Evans",
	"Hello, this is test account #1, the data is generated by https://cobbl.io",
	"female",
	"1990-06-05",
	"avatar6",
	"2025-06-19 22:49:50.361243+00:00"
),
(
	"480121f3-fa78-4696-ac7a-c78f7850e9d3",
	"jeward@live.com",
	"uppityrock",
	"$2b$12$QHY0lVlgooOXmRC6i7lMHOH9tO4dJSMwVC3tz.ICx8iAcxhGx6oBW",
	"Jonathan Ward",
	"Hello, this is test account #10, the data is generated by https://cobbl.io",
	"male",
	"1997-12-29",
	"avatar3",
	"2025-06-19 22:49:50.861243+00:00"
);

INSERT INTO user_privileges (user_id, privilege_id, created_at) VALUES
('3e8e14d4-b252-461b-9e76-1f143079cc9f', '928c3455-4d4c-11f0-9131-9a0ef0f53929', "2025-06-19 22:49:47.361243+00:00"),
('31512621-10b4-4951-a339-3d2e505978c3', '928c3455-4d4c-11f0-9131-9a0ef0f53929', "2025-06-19 22:49:48.361243+00:00"),
('c4c0b028-9e89-4d16-a21d-dd9368831f7f', '928c3455-4d4c-11f0-9131-9a0ef0f53929', "2025-06-19 22:49:49.361243+00:00"),
('270b45d1-0761-4636-8959-a3485e70b137', '928c3455-4d4c-11f0-9131-9a0ef0f53929', "2025-06-19 22:49:50.361243+00:00"),
('494646c1-0ec4-48de-a0cc-11f40ce527fa', '928c3455-4d4c-11f0-9131-9a0ef0f53929', "2025-06-19 22:49:51.361243+00:00"),
('b0407a9f-b516-4b45-b5a0-c1b52569fec8', '928c3455-4d4c-11f0-9131-9a0ef0f53929', "2025-06-19 22:49:52.361243+00:00"),
('72522e8a-e191-402f-bb19-ded1a1a11a7d', '928c3455-4d4c-11f0-9131-9a0ef0f53929', "2025-06-19 22:49:53.361243+00:00"),
('4441348d-4e0e-4cac-91f5-e2e4aeedf795', '928c3455-4d4c-11f0-9131-9a0ef0f53929', "2025-06-19 22:49:54.361243+00:00"),
('1572aedc-9b58-4aff-958f-18c26c4b0241', '928c3455-4d4c-11f0-9131-9a0ef0f53929', "2025-06-19 22:49:55.361243+00:00"),
('480121f3-fa78-4696-ac7a-c78f7850e9d3', '928c3455-4d4c-11f0-9131-9a0ef0f53929', "2025-06-19 22:49:56.361243+00:00");
