INSERT INTO users (id, email, username, password, fullname, about_me, gender, date_of_birth, avatar_type)
VALUES
(
	"54165a2b-2062-480c-a400-a00d06e471c0",
	"rebecca_mitchell@live.com",
	"jollybadge",
	"$2b$12$Rz/KIslm9HZ.rcco/xnDKOP0XVd90wfuGcz72Sid.iRYrQ1nTbdZ6",
	"Rebecca Mitchell",
	"Hello, this is test account #6, the data is generated by https://cobbl.io",
	"female",
	"2014-09-21",
	"avatar8"
),
(
	"0edb811c-350a-47d7-bbec-daecd8996ab1",
	"owenrcollins@yahoo.com",
	"mistycrate",
	"$2b$12$XQm6VFiy3022kjuCqZeVPOqoTAvjH6Sxnnc5TiYQ5xhcwwM3UHQgS",
	"Owen Collins",
	"Hello, this is test account #2, the data is generated by https://cobbl.io",
	"male",
	"1999-09-05",
	"avatar5"
),
(
	"1b2e1143-59da-440f-b125-55d11306cfd9",
	"s_m_lopez@rocketmail.com",
	"bewilderedshade",
	"$2b$12$QFVEsOuN0PF874FgtDcfV.7mqsFfk7rD4dQ3rSkOlv.kp7Os64x.m",
	"Stephanie Lopez",
	"Hello, this is test account #5, the data is generated by https://cobbl.io",
	"female",
	"2021-03-19",
	"avatar10"
),
(
	"702c63e8-d7f8-4974-8095-95af896a2b0c",
	"jdrichardson@rocketmail.com",
	"dustyshelf",
	"$2b$12$AyPPJ89ibvEObNBo72WD4.9nP52ukuUxl5YF0LfubNxZ6FZxQbL9u",
	"Joseph Richardson",
	"Hello, this is test account #9, the data is generated by https://cobbl.io",
	"male",
	"2010-12-07",
	"avatar1"
),
(
	"aae81551-c0b3-408c-b768-077e9130e426",
	"lking@hotmail.com",
	"stupendousliquid",
	"$2b$12$lc/MA6/2a1bbpgcS4.tQ4u6St0ysKncEBAFhdMdphfnzvhVIsyPv.",
	"Lillian King",
	"Hello, this is test account #7, the data is generated by https://cobbl.io",
	"female",
	"2005-06-21",
	"avatar6"
),
(
	"04f9501f-b857-4654-9661-c5a7d4c901f9",
	"jasminemayperez@outlook.com",
	"feignedfrog",
	"$2b$12$9OAhug0kbVYhuYVEX5zh4.KxiqvY23wycJG2Df81xTAmZjhp3OA0m",
	"Jasmine Perez",
	"Hello, this is test account #8, the data is generated by https://cobbl.io",
	"female",
	"2006-12-20",
	"avatar9"
),
(
	"ffc7b0df-2fe0-4369-9c52-1096c5955c5d",
	"ahall@yahoo.com",
	"tritehoney",
	"$2b$12$I.QPlOyP.BcGMbwGQE4TQ.WlrlyxUYaSan9sCPzN27jt6qg440HU2",
	"Alyssa Hall",
	"Hello, this is test account #4, the data is generated by https://cobbl.io",
	"female",
	"1993-01-11",
	NULL
),
(
	"54c1b625-416b-4e36-b41c-87b771eb0c7c",
	"ava.morgan@aol.com",
	"quicksupport",
	"$2b$12$wGkR4JhlaPgz9UAJWaEqUOMcCh88vGvY172U./xZoAeavXe3/wUD2",
	"Ava Morgan",
	"Hello, this is test account #3, the data is generated by https://cobbl.io",
	"female",
	"2012-06-12",
	"avatar7"
),
(
	"c2bfca24-13a2-49fa-a49c-affcbda94ad6",
	"l_evans@rocketmail.com",
	"miniatureriver",
	"$2b$12$b1Su3mqcAzvS0MEC5oJEROhvsK5Br59SNcRfyVrhuFHTvQVkVJmRW",
	"Layla Evans",
	"Hello, this is test account #1, the data is generated by https://cobbl.io",
	"female",
	"1990-06-05",
	"avatar6"
),
(
	"cd6df115-6918-463f-98f6-cb6c9dbb170b",
	"jeward@live.com",
	"uppityrock",
	"$2b$12$uvuPFkIIiK.ejZ1Ch42gnudE2LjZY0xsjp.ij/pdnQOKoTra65mrW",
	"Jonathan Ward",
	"Hello, this is test account #10, the data is generated by https://cobbl.io",
	"male",
	"1997-12-29",
	"avatar3"
);

INSERT INTO user_privileges (user_id, privilege_id) VALUES
('54165a2b-2062-480c-a400-a00d06e471c0', '928c3455-4d4c-11f0-9131-9a0ef0f53929'),
('0edb811c-350a-47d7-bbec-daecd8996ab1', '928c3455-4d4c-11f0-9131-9a0ef0f53929'),
('1b2e1143-59da-440f-b125-55d11306cfd9', '928c3455-4d4c-11f0-9131-9a0ef0f53929'),
('702c63e8-d7f8-4974-8095-95af896a2b0c', '928c3455-4d4c-11f0-9131-9a0ef0f53929'),
('aae81551-c0b3-408c-b768-077e9130e426', '928c3455-4d4c-11f0-9131-9a0ef0f53929'),
('04f9501f-b857-4654-9661-c5a7d4c901f9', '928c3455-4d4c-11f0-9131-9a0ef0f53929'),
('ffc7b0df-2fe0-4369-9c52-1096c5955c5d', '928c3455-4d4c-11f0-9131-9a0ef0f53929'),
('54c1b625-416b-4e36-b41c-87b771eb0c7c', '928c3455-4d4c-11f0-9131-9a0ef0f53929'),
('c2bfca24-13a2-49fa-a49c-affcbda94ad6', '928c3455-4d4c-11f0-9131-9a0ef0f53929'),
('cd6df115-6918-463f-98f6-cb6c9dbb170b', '928c3455-4d4c-11f0-9131-9a0ef0f53929');
